package fluffy.devices;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;

import javax.swing.JButton;
import javax.swing.JTextField;

import fluffy.os.FProcess;
import fluffy.os.FluffyOS;
import fluffy.os.FluffyOS.ResName;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author karolis
 */
public class InputPanel extends javax.swing.JPanel {

	private static final long serialVersionUID = 4668104880966701462L;



	private FluffyOS os;
    
    /**
     * Creates new form inputPanel
     */
    public InputPanel() {
        initComponents();
    }

    public void initInput(FProcess initializer){
    	String tmp = initializer.pDesc.intId + ":" +
    			initializer.pDesc.extId + ":" +
    			initializer.pDesc.pName;
        jLabel1.setText(tmp);
        inputField.setEditable(true);
    }
    
    public void setOS(FluffyOS os){
        this.os = os;
    }
    
    public JTextField getInpField(){
		return inputField;
    }
    
    public JButton getButton(){
		return enterBut;
    }
    
    public ActionListener usrAL = new ActionListener() {
		@Override
		public void actionPerformed(ActionEvent e) {
			String tmp = inputField.getText();
			os.createResource(
					os.starStopProc, ResName.IVEDIMO_SRAUTAS2, tmp);
			jLabel1.setText("");
			inputField.setText("");
			inputField.setEditable(false);
		}
	};
	
	
	
	public ActionListener sysAL = new ActionListener() {
		@Override
		public void actionPerformed(ActionEvent e) {
			String tmp = inputField.getText();
			String prefix = FluffyOS.FP_PREFIX;
			String fp = prefix + tmp + FluffyOS.FP_END;
			
			File f = new File(fp);
			if (f.exists()){
				os.createResource(
					os.starStopProc, ResName.IVEDIMO_SRAUTAS, new File(fp));
				os.printStuffDevice("SUCCESS: " + fp + " loaded :(");
			} else {
				os.printStuffDevice("ERROR: " + fp + " does not exist :(");
			}
		}
	};
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputField = new javax.swing.JTextField();
        enterBut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(400, 40));

        inputField.setName("inputField"); // NOI18N

        enterBut.setText("Enter");
        enterBut.setName("enterBut"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(inputField, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enterBut, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 16, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(enterBut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputField, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enterBut;
    private javax.swing.JTextField inputField;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
