/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package fluffy.gui;

import fluffy.os.FluffyOS;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * 
 * @author karolis
 */
public class FluffyControllsPanel extends javax.swing.JPanel {

	private static final long serialVersionUID = 5845827341376967882L;
	private FluffyOS os;

	public FluffyControllsPanel() {
		initComponents();
		initComponentListeners();
	}

	private void initComponentListeners() {
		setSpeedBut.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				String tmp = speedField.getText();
				int newSpeed;
				try {
					newSpeed = Integer.parseInt(tmp);
				} catch (NumberFormatException ex) {
					return;
				}

				FluffyOS.SPEED = newSpeed;
			}
		});

		startBut.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				os.stopOS = false;
				startBut.setEnabled(false);
				resetBut.setEnabled(false);
				Thread osThread = new Thread(os);
				osThread.start();
			}
		});

		stopBut.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				startBut.setEnabled(true);
				os.stopOS = true;
				resetBut.setEnabled(true);
			}
		});

		resetBut.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				os.reset();
				startBut.setEnabled(true);
			}
		});

		mosEndBut.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				os.createResource(os.starStopProc,
						FluffyOS.ResName.MOS_PABAIGA, "end");
				resetBut.setEnabled(true);
			}
		});
	}

	public FluffyOS getOS() {
		return os;
	}

	public void setOS(FluffyOS os) {
		this.os = os;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		setSpeedBut = new javax.swing.JButton();
		speedField = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();
		startBut = new javax.swing.JButton();
		stopBut = new javax.swing.JButton();
		resetBut = new javax.swing.JButton();
		mosEndBut = new javax.swing.JButton();

		setSpeedBut.setText("Set");

		speedField.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				speedFieldActionPerformed(evt);
			}
		});

		jLabel1.setText("Speed:");

		startBut.setText("Start");

		stopBut.setText("Stop");

		resetBut.setText("Reset");

		mosEndBut.setText("MOSpabaiga");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(mosEndBut, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addComponent(resetBut, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addComponent(stopBut, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addComponent(startBut, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addGroup(
						layout.createSequentialGroup()
								.addComponent(jLabel1)
								.addGap(6, 6, 6)
								.addComponent(speedField,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										51,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(setSpeedBut)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addComponent(startBut)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														setSpeedBut,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														30,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														speedField,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel1))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(stopBut)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(resetBut)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(mosEndBut)));
	}// </editor-fold>//GEN-END:initComponents

	private void speedFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_speedFieldActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_speedFieldActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel jLabel1;
	private javax.swing.JButton mosEndBut;
	private javax.swing.JButton resetBut;
	private javax.swing.JButton setSpeedBut;
	private javax.swing.JTextField speedField;
	private javax.swing.JButton startBut;
	private javax.swing.JButton stopBut;
	// End of variables declaration//GEN-END:variables
}
